#Expected result - "CustomerForm"
POST http://127.0.0.1:8000/get_form/
Accept: application/json
Content-Type: text/plain

customer_email=test@mail.com&customer_date=11.11.2011


###
#Expected result - "UserRegister"
POST http://127.0.0.1:8000/get_form/
Accept: application/json
Content-Type: text/plain

user_email=test@mail.com&user_register_date=2022-12-10

###
#Expected result - {
#  "new_email": "email",
#  "new_order_date": "date"
#}
POST http://127.0.0.1:8000/get_form/
Accept: application/json
Content-Type: text/plain

new_email=test@mail.com&new_order_date=2022-12-12

